export const ADD_EXPRESSION = 'ADD_EXPRESSION';
export const REMOVE_EXPRESSION = 'REMOVE_EXPRESSION';
export const SET_CLAUSE_FACET = 'SET_CLAUSE_FACET';
export const SET_CLAUSE_VALUE = 'SET_CLAUSE_VALUE';
export const SET_CLAUSE_OPERATOR = 'SET_CLAUSE_OPERATOR';
export const SET_FUSE_ENDPOINT = 'SET_FUSE_ENDPOINT';
export const DIAL_FUSE = 'DIAL_FUSE';
export const GET_RESULTS = 'GET_RESULTS';
